import Foundation
import SwiftUI
import Combine

class Localization: ObservableObject {
    static let shared = Localization()
    
    @Published var currentLanguage: Language = GameSettingsManager.shared.language
    private var cancellables = Set<AnyCancellable>()
    
    // Rečnici prevoda za svaki jezik
    private let translations: [Language: [String: String]] = [
        .serbian: [
            "settings": "Podešavanja",
            "close": "Zatvori",
            "apply_start_new": "Primeni i započni novu igru",
            "board_size": "Veličina table",
            "appearance": "Izgled",
            "theme": "Tema",
            "time_limit": "Vreme za potez",
            "time_limit_option": "Ograničenje vremena",
            "opponent": "Protivnik",
            "play_against_computer": "Igraj protiv računara",
            "difficulty": "Težina",
            "ai_team": "AI tim",
            "blue": "Plavi",
            "red": "Crveni",
            "ai_vs_ai": "AI vs AI mod",
            "second_ai_difficulty": "Težina drugog AI",
            "first_move": "Prvi na potezu",
            "sound_vibration": "Zvuk i vibracija",
            "sound_effects": "Zvučni efekti",
            "vibration": "Vibracija",
            "language": "Jezik",
            "new_game": "Nova igra",
            "your_turn": "Vi ste na potezu",
            "ai_turn": "AI na potezu",
            "ai_thinking": "AI razmišlja...",
            "turn": "Na potezu",
            "no_valid_moves": "Nema validnih poteza!",
            "blue_timeout": "Isteklo vreme plavom igraču!",
            "red_timeout": "Isteklo vreme crvenom igraču!",
            "game_over": "Igra je završena!",
            "winner": "Pobednik",
            "easy": "Lako",
            "medium": "Srednje",
            "hard": "Teško",
            "no_limit": "Bez ograničenja",
            "minute": "minut",
            "minutes": "minuta",
            "ocean": "Okean",
            "sunset": "Zalazak sunca",
            "forest": "Šuma",
            "galaxy": "Galaksija",
            "classic": "Klasična",
            "save": "Sačuvaj",
            "load": "Učitaj",
            "help": "Uputstvo",
            "achievements": "Postignuća",
            "completed": "Završeno",
            "in_progress": "U toku",
            "locked": "Zaključano",
            "achievement_unlocked": "Postignuće otključano!",
            
            // Achievement titles
            "first_win_title": "Prvi trijumf",
            "win_streak_title": "Pobednički niz",
            "beat_hard_ai_title": "Pobednik AI-ja",
            "quick_win_title": "Brza pobeda",
            "corner_master_title": "Majstor uglova",
            "blocking_master_title": "Majstor blokiranja",
            "timeout_win_title": "Pobeda na vreme",
            "perfect_game_title": "Savršena igra",
            "ai_vs_ai_watcher_title": "AI posmatrač",
            "play_all_sizes_title": "Istraživač",
            
            // Achievement descriptions
            "first_win_desc": "Ostvari svoju prvu pobedu",
            "win_streak_desc": "Pobedi 5 puta zaredom",
            "beat_hard_ai_desc": "Pobedi AI na teškom nivou",
            "quick_win_desc": "Pobedi u 10 ili manje poteza",
            "corner_master_desc": "Pobedi 10 puta koristeći ugaona polja",
            "blocking_master_desc": "Pobedi 15 puta blokiranjem protivnika",
            "timeout_win_desc": "Pobedi 3 puta na vreme",
            "perfect_game_desc": "Pobedi tako da protivnik ima 3 ili manje poteza",
            "ai_vs_ai_watcher_desc": "Pogledaj 5 AI vs AI partija",
            "play_all_sizes_desc": "Igraj na svim veličinama table",
            "how_to_play": "Kako igrati Squart",
            "about_game": "O igri",
            "game_rules": "Pravila igre",
            "how_to_win": "Kako pobediti",
            "ai_opponent": "AI protivnik",
            "game_tips": "Saveti za igru",
            "about_game_text": "Squart je logička igra za dva igrača inspirisana igrom TicTacToe, ali sa izmenjenim pravilima. Cilj igre je da ostavite protivnika bez validnih poteza.",
            "board_description": "Na tabli se nalaze bela (prazna) i crna (blokirana) polja. Crna polja se ne mogu koristiti za igru.",
            "rules_blue_first": " Plavi igrač igra prvi u prvoj partiji, a zatim se naizmenično menja ko igra prvi",
            "rules_blue_move": " Plavi igrač postavlja plave žetone horizontalno - kada klikne na prazno polje, žeton zauzima to polje i polje desno od njega",
            "rules_red_move": " Crveni igrač postavlja crvene žetone vertikalno - kada klikne na prazno polje, žeton zauzima to polje i polje ispod njega",
            "rules_alternating": " Igrači se naizmenično smenjuju",
            "rules_blocked_fields": " Nije dozvoljeno postavljanje žetona na crna polja ili polja koja su već zauzeta",
            "rules_valid_move": " Potez je validan samo ako ima dovoljno prostora za ceo žeton (dva polja)",
            "rules_time_limit": " Ako je uključeno vremensko ograničenje, svaki igrač ima ograničeno vreme za celu partiju (kao u šahu). Vreme se meri samo dok je igrač na potezu.",
            "win_ways": "Igru možete pobediti na dva načina:",
            "win_no_moves": "1. Dovesti protivnika u situaciju da ne može da odigra validan potez. Pobednik je igrač koji je odigrao poslednji validni potez.",
            "win_timeout": "2. Kada protivniku istekne vreme (ako je uključeno vremensko ograničenje). Ako igraču istekne vreme na njegovom satu, protivnik je pobednik.",
            "ai_intro": "Pored igre protiv drugog igrača, možete igrati i protiv računara (AI):",
            "ai_settings": " AI opciju možete uključiti u podešavanjima",
            "ai_team_select": " Možete izabrati da AI igra kao plavi ili crveni tim",
            "ai_difficulty": " Dostupna su tri nivoa težine: Lako, Srednje i Teško",
            "ai_first_move": " Prvi igrač se naizmenično menja nakon svake partije",
            "ai_turn_wait": " Kada je AI na potezu, ne možete vi odigrati njegov potez",
            "ai_vs_ai_mode": " AI vs AI mod: Možete aktivirati i opciju da dva AI igrača igraju jedan protiv drugog",
            "ai_vs_ai_difficulty": " U AI vs AI modu, možete izabrati težinu za svakog od AI igrača posebno",
            "ai_advanced": " Napredni AI: Možete aktivirati naprednu veštačku inteligenciju koja koristi sofisticiranije strategije",
            "ai_vs_ai_learning": " AI vs AI mod je koristan za učenje strategije i tehnika igre",
            "tips_planning": " Planirajte unapred - razmišljajte o tome kako će vaš potez uticati na moguće poteze protivnika",
            "tips_blocking": " Pokušajte da protivniku blokirate prostor za postavljanje njegovog žetona",
            "tips_edges": " Često je bolje igrati na ivicama table nego u sredini, posebno u ranim fazama igre",
            "tips_blocked_fields": " Obratite pažnju na crna polja - ona mogu biti korisna ili štetna za vašu strategiju",
            "tips_corners": " Kontrola uglova table često donosi prednost u kasnim fazama igre",
            "tips_valid_moves": " Pratite koliko validnih poteza ima protivnik i pokušajte da ih smanjite"
        ],
        .english: [
            "settings": "Settings",
            "close": "Close",
            "apply_start_new": "Apply and Start New Game",
            "board_size": "Board Size",
            "appearance": "Appearance",
            "theme": "Theme",
            "time_limit": "Time Limit",
            "time_limit_option": "Time Limit Option",
            "opponent": "Opponent",
            "play_against_computer": "Play Against Computer",
            "difficulty": "Difficulty",
            "ai_team": "AI Team",
            "blue": "Blue",
            "red": "Red",
            "ai_vs_ai": "AI vs AI Mode",
            "second_ai_difficulty": "Second AI Difficulty",
            "first_move": "First Move",
            "sound_vibration": "Sound & Vibration",
            "sound_effects": "Sound Effects",
            "vibration": "Vibration",
            "language": "Language",
            "new_game": "New Game",
            "your_turn": "Your Turn",
            "ai_turn": "AI's Turn",
            "ai_thinking": "AI is thinking...",
            "turn": "Turn",
            "no_valid_moves": "No Valid Moves!",
            "blue_timeout": "Blue Player Timeout!",
            "red_timeout": "Red Player Timeout!",
            "game_over": "Game Over!",
            "winner": "Winner",
            "easy": "Easy",
            "medium": "Medium",
            "hard": "Hard",
            "no_limit": "No Limit",
            "minute": "minute",
            "minutes": "minutes",
            "ocean": "Ocean",
            "sunset": "Sunset",
            "forest": "Forest",
            "galaxy": "Galaxy",
            "classic": "Classic",
            "save": "Save",
            "load": "Load",
            "help": "Help",
            "achievements": "Achievements",
            "completed": "Completed",
            "in_progress": "In Progress",
            "locked": "Locked",
            "achievement_unlocked": "Achievement Unlocked!",
            
            // Achievement titles
            "first_win_title": "First Win",
            "win_streak_title": "Win Streak",
            "beat_hard_ai_title": "Beat Hard AI",
            "quick_win_title": "Quick Win",
            "corner_master_title": "Corner Master",
            "blocking_master_title": "Blocking Master",
            "timeout_win_title": "Timeout Win",
            "perfect_game_title": "Perfect Game",
            "ai_vs_ai_watcher_title": "AI Watcher",
            "play_all_sizes_title": "Explorer",
            
            // Achievement descriptions
            "first_win_desc": "Achieve your first win",
            "win_streak_desc": "Win 5 games in a row",
            "beat_hard_ai_desc": "Beat an AI on hard difficulty",
            "quick_win_desc": "Win in 10 or fewer moves",
            "corner_master_desc": "Win 10 games using corner spaces",
            "blocking_master_desc": "Win 15 games by blocking your opponent",
            "timeout_win_desc": "Win 3 games on time",
            "perfect_game_desc": "Win by having 3 or fewer moves",
            "ai_vs_ai_watcher_desc": "Watch 5 AI vs AI games",
            "play_all_sizes_desc": "Play on all board sizes",
            "how_to_play": "How to Play Squart",
            "about_game": "About the Game",
            "game_rules": "Game Rules",
            "how_to_win": "How to Win",
            "ai_opponent": "AI Opponent",
            "game_tips": "Game Tips",
            "about_game_text": "Squart is a two-player logic game inspired by TicTacToe but with modified rules. The goal is to leave your opponent without valid moves.",
            "board_description": "The board contains white (empty) and black (blocked) fields. Black fields cannot be used for play.",
            "rules_blue_first": " Blue player goes first in the first game, then alternates who goes first",
            "rules_blue_move": " Blue player places blue tokens horizontally - when clicking an empty field, the token occupies that field and the field to its right",
            "rules_red_move": " Red player places red tokens vertically - when clicking an empty field, the token occupies that field and the field below it",
            "rules_alternating": " Players take turns",
            "rules_blocked_fields": " Placing tokens on black fields or already occupied fields is not allowed",
            "rules_valid_move": " A move is valid only if there is enough space for the entire token (two fields)",
            "rules_time_limit": " If time limit is enabled, each player has limited time for the entire game (like in chess). Time is only measured while the player is on the move.",
            "win_ways": "You can win the game in two ways:",
            "win_no_moves": "1. Leave your opponent without valid moves. The winner is the player who made the last valid move.",
            "win_timeout": "2. When the opponent runs out of time (if time limit is enabled). If a player runs out of time on their clock, the opponent is the winner.",
            "ai_intro": "Besides playing against another player, you can also play against the computer (AI):",
            "ai_settings": " You can enable AI option in settings",
            "ai_team_select": " You can choose whether AI plays as blue or red team",
            "ai_difficulty": " Three difficulty levels are available: Easy, Medium, and Hard",
            "ai_first_move": " First player alternates after each game",
            "ai_turn_wait": " When AI is on the move, you cannot make its move",
            "ai_vs_ai_mode": " AI vs AI mode: You can also activate the option for two AI players to play against each other",
            "ai_vs_ai_difficulty": " In AI vs AI mode, you can select difficulty for each AI player separately",
            "ai_advanced": " Advanced AI: You can activate advanced artificial intelligence that uses more sophisticated strategies",
            "ai_vs_ai_learning": " AI vs AI mode is useful for learning game strategy and techniques",
            "tips_planning": " Plan ahead - think about how your move will affect your opponent's possible moves",
            "tips_blocking": " Try to block your opponent's space for placing their token",
            "tips_edges": " It's often better to play on the edges of the board than in the center, especially in early game",
            "tips_blocked_fields": " Pay attention to black fields - they can be useful or harmful to your strategy",
            "tips_corners": " Control of board corners often brings advantage in late game",
            "tips_valid_moves": " Keep track of how many valid moves your opponent has and try to reduce them"
        ],
        .german: [
            "settings": "Einstellungen",
            "close": "Schließen",
            "apply_start_new": "Anwenden und Neues Spiel starten",
            "board_size": "Spielfeldgröße",
            "appearance": "Aussehen",
            "theme": "Thema",
            "time_limit": "Zeitlimit",
            "time_limit_option": "Zeitlimit-Option",
            "opponent": "Gegner",
            "play_against_computer": "Gegen Computer spielen",
            "difficulty": "Schwierigkeit",
            "ai_team": "KI-Team",
            "blue": "Blau",
            "red": "Rot",
            "ai_vs_ai": "KI gegen KI Modus",
            "second_ai_difficulty": "Schwierigkeit der zweiten KI",
            "first_move": "Erster Zug",
            "sound_vibration": "Ton & Vibration",
            "sound_effects": "Soundeffekte",
            "vibration": "Vibration",
            "language": "Sprache",
            "new_game": "Neues Spiel",
            "your_turn": "Du bist dran",
            "ai_turn": "KI ist dran",
            "ai_thinking": "KI denkt nach...",
            "turn": "Am Zug",
            "no_valid_moves": "Keine gültigen Züge!",
            "blue_timeout": "Zeitüberschreitung für Blau!",
            "red_timeout": "Zeitüberschreitung für Rot!",
            "game_over": "Spiel vorbei!",
            "winner": "Gewinner",
            "easy": "Leicht",
            "medium": "Mittel",
            "hard": "Schwer",
            "no_limit": "Kein Limit",
            "minute": "Minute",
            "minutes": "Minuten",
            "ocean": "Ozean",
            "sunset": "Sonnenuntergang",
            "forest": "Wald",
            "galaxy": "Galaxie",
            "classic": "Klassisch",
            "save": "Speichern",
            "load": "Laden",
            "help": "Hilfe",
            "achievements": "Erfolge",
            "completed": "Abgeschlossen",
            "in_progress": "In Bearbeitung",
            "locked": "Gesperrt",
            "achievement_unlocked": "Erfolg entsperrt!",
            
            // Achievement titles
            "first_win_title": "Erster Sieg",
            "win_streak_title": "Siegestränge",
            "beat_hard_ai_title": "AI-Sieg",
            "quick_win_title": "Schnell gewonnen",
            "corner_master_title": "Eckentrainer",
            "blocking_master_title": "Blocktrainer",
            "timeout_win_title": "Zeitgewinn",
            "perfect_game_title": "Perfekte Partie",
            "ai_vs_ai_watcher_title": "AI-Beobachter",
            "play_all_sizes_title": "Erkundiger",
            
            // Achievement descriptions
            "first_win_desc": "Deinen ersten Sieg erzielen",
            "win_streak_desc": "5 Siege hintereinander",
            "beat_hard_ai_desc": "Einen AI auf schwerem Level schlagen",
            "quick_win_desc": "In 10 oder weniger Zügen gewinnen",
            "corner_master_desc": "10 Siege gewinnen, indem Sie Eckfelder verwenden",
            "blocking_master_desc": "15 Siege gewinnen, indem Sie Ihren Gegner blockieren",
            "timeout_win_desc": "3 Siege gewinnen, bevor Ihr Gegner Zeit hat",
            "perfect_game_desc": "Gewinnen, indem Sie 3 oder weniger Züge haben",
            "ai_vs_ai_watcher_desc": "5 AI vs AI Spiele beobachten",
            "play_all_sizes_desc": "Auf allen Spielfeldern spielen",
            "how_to_play": "Wie man Squart spielt",
            "about_game": "Über das Spiel",
            "game_rules": "Spielregeln",
            "how_to_win": "Wie man gewinnt",
            "ai_opponent": "KI-Gegner",
            "game_tips": "Spieltipps",
            "about_game_text": "Squart ist ein Logikspiel für zwei Spieler, inspiriert von TicTacToe, aber mit modifizierten Regeln. Das Ziel ist es, den Gegner ohne gültige Züge zu lassen.",
            "board_description": "Das Spielfeld enthält weiße (leere) und schwarze (blockierte) Felder. Schwarze Felder können nicht zum Spielen verwendet werden.",
            "rules_blue_first": " Der blaue Spieler beginnt im ersten Spiel, dann wird abwechselnd bestimmt, wer beginnt",
            "rules_blue_move": " Der blaue Spieler platziert blaue Steine horizontal - beim Klicken auf ein leeres Feld besetzt der Stein dieses Feld und das Feld rechts daneben",
            "rules_red_move": " Der rote Spieler platziert rote Steine vertikal - beim Klicken auf ein leeres Feld besetzt der Stein dieses Feld und das Feld darunter",
            "rules_alternating": " Die Spieler sind abwechselnd am Zug",
            "rules_blocked_fields": " Das Platzieren von Steinen auf schwarzen oder bereits besetzten Feldern ist nicht erlaubt",
            "rules_valid_move": " Ein Zug ist nur gültig, wenn genügend Platz für den gesamten Stein (zwei Felder) vorhanden ist",
            "rules_time_limit": " Wenn das Zeitlimit aktiviert ist, hat jeder Spieler begrenzte Zeit für das gesamte Spiel (wie beim Schach). Die Zeit wird nur gemessen, während der Spieler am Zug ist.",
            "win_ways": "Sie können das Spiel auf zwei Arten gewinnen:",
            "win_no_moves": "1. Lassen Sie Ihren Gegner ohne gültige Züge. Gewinner ist der Spieler, der den letzten gültigen Zug gemacht hat.",
            "win_timeout": "2. Wenn dem Gegner die Zeit ausgeht (wenn Zeitlimit aktiviert ist). Wenn einem Spieler die Zeit auf seiner Uhr ausgeht, ist der Gegner der Gewinner.",
            "ai_intro": "Neben dem Spielen gegen einen anderen Spieler können Sie auch gegen den Computer (KI) spielen:",
            "ai_settings": " Sie können die KI-Option in den Einstellungen aktivieren",
            "ai_team_select": " Sie können wählen, ob die KI als blaues oder rotes Team spielt",
            "ai_difficulty": " Drei Schwierigkeitsgrade sind verfügbar: Leicht, Mittel und Schwer",
            "ai_first_move": " Der erste Spieler wechselt nach jedem Spiel",
            "ai_turn_wait": " Wenn die KI am Zug ist, können Sie ihren Zug nicht machen",
            "ai_vs_ai_mode": " KI gegen KI Modus: Sie können auch die Option aktivieren, dass zwei KI-Spieler gegeneinander spielen",
            "ai_vs_ai_difficulty": " Im KI gegen KI Modus können Sie die Schwierigkeit für jeden KI-Spieler separat auswählen",
            "ai_advanced": " Fortgeschrittene KI: Sie können fortgeschrittene künstliche Intelligenz aktivieren, die raffiniertere Strategien verwendet",
            "ai_vs_ai_learning": " KI gegen KI Modus ist nützlich zum Lernen von Spielstrategien und -techniken",
            "tips_planning": " Planen Sie voraus - denken Sie darüber nach, wie Ihr Zug die möglichen Züge Ihres Gegners beeinflussen wird",
            "tips_blocking": " Versuchen Sie, den Platz Ihres Gegners für das Platzieren seines Steins zu blockieren",
            "tips_edges": " Es ist oft besser, an den Rändern des Spielfelds zu spielen als in der Mitte, besonders in der frühen Spielphase",
            "tips_blocked_fields": " Achten Sie auf schwarze Felder - sie können nützlich oder schädlich für Ihre Strategie sein",
            "tips_corners": " Die Kontrolle über die Ecken des Spielfelds bringt oft Vorteile in der späten Spielphase",
            "tips_valid_moves": " Behalten Sie im Auge, wie viele gültige Züge Ihr Gegner hat, und versuchen Sie, diese zu reduzieren"
        ],
        .russian: [
            "settings": "Настройки",
            "close": "Закрыть",
            "apply_start_new": "Применить и начать новую игру",
            "board_size": "Размер доски",
            "appearance": "Внешний вид",
            "theme": "Тема",
            "time_limit": "Ограничение времени",
            "time_limit_option": "Вариант ограничения времени",
            "opponent": "Противник",
            "play_against_computer": "Играть против компьютера",
            "difficulty": "Сложность",
            "ai_team": "Команда ИИ",
            "blue": "Синий",
            "red": "Красный",
            "ai_vs_ai": "Режим ИИ против ИИ",
            "second_ai_difficulty": "Сложность второго ИИ",
            "first_move": "Первый ход",
            "sound_vibration": "Звук и вибрация",
            "sound_effects": "Звуковые эффекты",
            "vibration": "Вибрация",
            "language": "Язык",
            "new_game": "Новая игра",
            "your_turn": "Ваш ход",
            "ai_turn": "Ход ИИ",
            "ai_thinking": "ИИ думает...",
            "turn": "Ход",
            "no_valid_moves": "Нет допустимых ходов!",
            "blue_timeout": "Время синего игрока истекло!",
            "red_timeout": "Время красного игрока истекло!",
            "game_over": "Игра окончена!",
            "winner": "Победитель",
            "easy": "Легкий",
            "medium": "Средний",
            "hard": "Сложный",
            "no_limit": "Без ограничений",
            "minute": "минута",
            "minutes": "минут",
            "ocean": "Океан",
            "sunset": "Закат",
            "forest": "Лес",
            "galaxy": "Галактика",
            "classic": "Классический",
            "save": "Сохранить",
            "load": "Загрузить",
            "help": "Помощь",
            "achievements": "Постижения",
            "completed": "Завершено",
            "in_progress": "В процессе",
            "locked": "Заблокировано",
            "achievement_unlocked": "Постижение разблокировано!",
            
            // Achievement titles
            "first_win_title": "Первая победа",
            "win_streak_title": "Победный ряд",
            "beat_hard_ai_title": "Победа над AI",
            "quick_win_title": "Быстрая победа",
            "corner_master_title": "Мастер углов",
            "blocking_master_title": "Мастер блокировки",
            "timeout_win_title": "Победа по времени",
            "perfect_game_title": "Идеальная игра",
            "ai_vs_ai_watcher_title": "Наблюдатель AI vs AI",
            "play_all_sizes_title": "Исследователь",
            
            // Achievement descriptions
            "first_win_desc": "Достигните своей первой победы",
            "win_streak_desc": "Победите 5 раз подряд",
            "beat_hard_ai_desc": "Победите AI на сложном уровне",
            "quick_win_desc": "Победите в 10 или меньше ходов",
            "corner_master_desc": "Победите 10 раз, используя угловые поля",
            "blocking_master_desc": "Победите 15 раз, блокируя противника",
            "timeout_win_desc": "Победите 3 раза, пока противник не успеет",
            "perfect_game_desc": "Победите, если у вашего противника 3 или меньше ходов",
            "ai_vs_ai_watcher_desc": "Наблюдайте 5 игр AI vs AI",
            "play_all_sizes_desc": "Играйте на всех размерах доски",
            "how_to_play": "Как играть в Squart",
            "about_game": "Об игре",
            "game_rules": "Правила игры",
            "how_to_win": "Как победить",
            "ai_opponent": "ИИ-противник",
            "game_tips": "Советы по игре",
            "about_game_text": "Squart - это логическая игра для двух игроков, вдохновленная игрой Крестики-нолики, но с измененными правилами. Цель игры - оставить противника без допустимых ходов.",
            "board_description": "На доске есть белые (пустые) и черные (заблокированные) поля. Черные поля нельзя использовать для игры.",
            "rules_blue_first": " Синий игрок ходит первым в первой партии, затем чередуется, кто ходит первым",
            "rules_blue_move": " Синий игрок размещает синие фишки горизонтально - при клике на пустое поле фишка занимает это поле и поле справа от него",
            "rules_red_move": " Красный игрок размещает красные фишки вертикально - при клике на пустое поле фишка занимает это поле и поле под ним",
            "rules_alternating": " Игроки ходят по очереди",
            "rules_blocked_fields": " Размещение фишек на черных или уже занятых полях запрещено",
            "rules_valid_move": " Ход допустим только если есть достаточно места для всей фишки (два поля)",
            "rules_time_limit": " Если включено ограничение времени, у каждого игрока ограниченное время на всю партию (как в шахматах). Время отсчитывается только когда игрок на ходу.",
            "win_ways": "Вы можете выиграть игру двумя способами:",
            "win_no_moves": "1. Оставить противника без допустимых ходов. Победителем становится игрок, сделавший последний допустимый ход.",
            "win_timeout": "2. Когда у противника заканчивается время (если включено ограничение времени). Если у игрока заканчивается время на его часах, победителем становится противник.",
            "ai_intro": "Помимо игры против другого игрока, вы также можете играть против компьютера (ИИ):",
            "ai_settings": " Вы можете включить опцию ИИ в настройках",
            "ai_team_select": " Вы можете выбрать, будет ли ИИ играть за синюю или красную команду",
            "ai_difficulty": " Доступны три уровня сложности: Легкий, Средний и Сложный",
            "ai_first_move": " Первый ход чередуется после каждой партии",
            "ai_turn_wait": " Когда ИИ на ходу, вы не можете сделать его ход",
            "ai_vs_ai_mode": " Режим ИИ против ИИ: вы также можете активировать опцию для игры двух ИИ-игроков друг против друга",
            "ai_vs_ai_difficulty": " В режиме ИИ против ИИ вы можете выбрать сложность для каждого ИИ-игрока отдельно",
            "ai_advanced": " Продвинутый ИИ: вы можете активировать продвинутый искусственный интеллект, использующий более сложные стратегии",
            "ai_vs_ai_learning": " Режим ИИ против ИИ полезен для изучения стратегии и техник игры",
            "tips_planning": " Планируйте заранее - думайте о том, как ваш ход повлияет на возможные ходы противника",
            "tips_blocking": " Старайтесь блокировать пространство противника для размещения его фишки",
            "tips_edges": " Часто лучше играть по краям доски, чем в центре, особенно в начале игры",
            "tips_blocked_fields": " Обращайте внимание на черные поля - они могут быть полезны или вредны для вашей стратегии",
            "tips_corners": " Контроль углов доски часто дает преимущество в конце игры",
            "tips_valid_moves": " Следите за количеством допустимых ходов у противника и старайтесь их уменьшить"
        ],
        .chinese: [
            "settings": "设置",
            "close": "关闭",
            "apply_start_new": "应用并开始新游戏",
            "board_size": "棋盘大小",
            "appearance": "外观",
            "theme": "主题",
            "time_limit": "时间限制",
            "time_limit_option": "时间限制选项",
            "opponent": "对手",
            "play_against_computer": "与电脑对战",
            "difficulty": "难度",
            "ai_team": "AI队伍",
            "blue": "蓝色",
            "red": "红色",
            "ai_vs_ai": "AI对战AI模式",
            "second_ai_difficulty": "第二AI难度",
            "first_move": "先手",
            "sound_vibration": "声音和振动",
            "sound_effects": "音效",
            "vibration": "振动",
            "language": "语言",
            "new_game": "新游戏",
            "your_turn": "你的回合",
            "ai_turn": "AI回合",
            "ai_thinking": "AI思考中...",
            "turn": "回合",
            "no_valid_moves": "没有有效移动！",
            "blue_timeout": "蓝方超时！",
            "red_timeout": "红方超时！",
            "game_over": "游戏结束！",
            "winner": "获胜者",
            "easy": "简单",
            "medium": "中等",
            "hard": "困难",
            "no_limit": "无限制",
            "minute": "分钟",
            "minutes": "分钟",
            "ocean": "海洋",
            "sunset": "日落",
            "forest": "森林",
            "galaxy": "星系",
            "classic": "经典",
            "save": "保存",
            "load": "加载",
            "help": "帮助",
            "achievements": "成就",
            "completed": "已完成",
            "in_progress": "进行中",
            "locked": "已锁定",
            "achievement_unlocked": "成就已解锁！",
            
            // Achievement titles
            "first_win_title": "首次胜利",
            "win_streak_title": "连胜",
            "beat_hard_ai_title": "击败AI",
            "quick_win_title": "快速胜利",
            "corner_master_title": "角落大师",
            "blocking_master_title": "阻挡大师",
            "timeout_win_title": "时间胜利",
            "perfect_game_title": "完美游戏",
            "ai_vs_ai_watcher_title": "AI观察者",
            "play_all_sizes_title": "探险家",
            
            // Achievement descriptions
            "first_win_desc": "获得你的第一次胜利",
            "win_streak_desc": "连续赢得5场比赛",
            "beat_hard_ai_desc": "击败难度较高的AI",
            "quick_win_desc": "在10步或更少步数内获胜",
            "corner_master_desc": "在角落格子上赢得10场比赛",
            "blocking_master_desc": "在对手格子上赢得15场比赛",
            "timeout_win_desc": "在对手有时间之前赢得3场比赛",
            "perfect_game_desc": "在对手有3步或更少步数时获胜",
            "ai_vs_ai_watcher_desc": "观看5场AI vs AI比赛",
            "play_all_sizes_desc": "在所有棋盘大小上游戏",
            "how_to_play": "如何玩Squart",
            "about_game": "关于游戏",
            "game_rules": "游戏规则",
            "how_to_win": "如何获胜",
            "ai_opponent": "AI对手",
            "game_tips": "游戏技巧",
            "about_game_text": "Squart是一款受井字棋启发的双人逻辑游戏，但规则有所修改。游戏目标是让对手没有有效的移动。",
            "board_description": "棋盘上有白色（空）和黑色（已封锁）的格子。黑色格子不能用于游戏。",
            "rules_blue_first": " 蓝方在第一局中先手，之后轮流决定谁先手",
            "rules_blue_move": " 蓝方水平放置蓝色棋子 - 点击空格时，棋子占据该格子和其右侧的格子",
            "rules_red_move": " 红方垂直放置红色棋子 - 点击空格时，棋子占据该格子和其下方的格子",
            "rules_alternating": " 玩家轮流下棋",
            "rules_blocked_fields": " 不允许在黑色格子或已被占据的格子上放置棋子",
            "rules_valid_move": " 只有当有足够空间放置整个棋子（两个格子）时，移动才有效",
            "rules_time_limit": " 如果启用了时间限制，每个玩家在整个游戏中有有限的时间（如国际象棋）。时间只在玩家回合时计算。",
            "win_ways": "您可以通过两种方式获胜：",
            "win_no_moves": "1. 让对手没有有效的移动。最后做出有效移动的玩家获胜。",
            "win_timeout": "2. 当对手时间用完时（如果启用了时间限制）。如果玩家在其时钟上时间用完，对手获胜。",
            "ai_intro": "除了与另一位玩家对战外，您还可以与电脑（AI）对战：",
            "ai_settings": " 您可以在设置中启用AI选项",
            "ai_team_select": " 您可以选择AI是作为蓝方还是红方",
            "ai_difficulty": " 提供三个难度级别：简单、中等和困难",
            "ai_first_move": " 每局后轮流决定谁先手",
            "ai_turn_wait": " 当AI回合时，您不能替它下棋",
            "ai_vs_ai_mode": " AI对战AI模式：您还可以激活两个AI玩家相互对战的选项",
            "ai_vs_ai_difficulty": " 在AI对战AI模式中，您可以为每个AI玩家单独选择难度",
            "ai_advanced": " 高级AI：您可以激活使用更复杂策略的高级人工智能",
            "ai_vs_ai_learning": " AI对战AI模式有助于学习游戏策略和技巧",
            "tips_planning": " 提前计划 - 考虑您的移动将如何影响对手可能的移动",
            "tips_blocking": " 尝试阻止对手放置棋子的空间",
            "tips_edges": " 在游戏早期，通常最好在棋盘边缘而不是中心下棋",
            "tips_blocked_fields": " 注意黑色格子 - 它们可能对您的策略有利或有害",
            "tips_corners": " 在游戏后期，控制棋盘角落通常带来优势",
            "tips_valid_moves": " 跟踪对手有多少有效移动，并尝试减少它们"
        ]
    ]
    
    private init() {
        // Pratimo promene jezika
        NotificationCenter.default.publisher(for: Notification.Name("LanguageChanged"))
            .sink { [weak self] notification in
                if let language = notification.object as? Language {
                    self?.currentLanguage = language
                }
            }
            .store(in: &cancellables)
    }
    
    // Metoda za prevođenje teksta
    func localize(_ key: String) -> String {
        if let translation = translations[currentLanguage]?[key] {
            return translation
        }
        
        // Ako prevod ne postoji, vraćamo ključ
        return key
    }
}

// Extension za String koji omogućava laku lokalizaciju
extension String {
    var localized: String {
        return Localization.shared.localize(self)
    }
} 